export const GET_TESTS_REQUEST = 'GET_TESTS_REQUEST';
export const GET_TESTS_SUCCESS = 'GET_TESTS_SUCCESS';
export const GET_TESTS_FAIL = 'GET_TESTS_FAIL';

export const GET_TEST_REQUEST = 'GET_TEST_REQUEST';
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS';
export const GET_TEST_FAIL = 'GET_TEST_FAIL';
export const GET_TEST_RESET = 'GET_TEST_RESET';

export const GET_ACTIVE_TESTS_REQUEST = 'GET_ACTIVE_TESTS_REQUEST';
export const GET_ACTIVE_TESTS_SUCCESS = 'GET_ACTIVE_TESTS_SUCCESS';
export const GET_ACTIVE_TESTS_FAIL = 'GET_ACTIVE_TESTS_FAIL';

export const UPDATE_TEST_REQUEST = 'UPDATE_TEST_REQUEST';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_FAIL = 'UPDATE_TEST_FAIL';
export const UPDATE_TEST_RESET = 'UPDATE_TEST_RESET';

export const POST_TEST_REQUEST = 'POST_TEST_REQUEST';
export const POST_TEST_SUCCESS = 'POST_TEST_SUCCESS';
export const POST_TEST_FAIL = 'POST_TEST_FAIL';
